apiVersion: v1
kind: Service
metadata:
  name: acmecorp-developer-iq-auth-service
spec:
  selector:
    app: acmecorp-developer-iq-auth-service
  type: LoadBalancer
  ports:
  - protocol: TCP 
    port: 84
    targetPort: 84
